services:
  - type: web
    name: pumpkin-farm-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.api
    envVars:
      - key: PGRST_DB_URI
        sync: false
      - key: PGRST_DB_SCHEMAS
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: pumpkin_farm_db_user
      - key: DATABASE_URL
        sync: false

  - type: web
    name: pumpkin-farm-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_BASE
        sync: false
      - key: DATABASE_URL
        sync: false

databases:
  - name: pumpkin-farm-db
    plan: free
    postgresMajorVersion: 15
